# Generated by Django 3.0.8 on 2020-07-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
